#ifndef ENCODER_VIDEO_DEFINE
#define ENCODER_VIDEO_DEFINE

#include "hardware_acceleration.h"

namespace am {

	typedef enum {
		EID_VIDEO_X264  = HARDWARE_TYPE_UNKNOWN,
		EID_VIDEO_NVENC = HARDWARE_TYPE_NVENC,
		EID_VIDEO_QSV = HARDWARE_TYPE_QSV,
		EID_VIDEO_AMF = HARDWARE_TYPE_AMF,
		EID_VIDEO_VAAPI = HARDWARE_TYPE_VAAPI,
	}ENCODER_VIDEO_ID;

	typedef enum {
		ET_VIDEO_SOFT,
		ET_VIDEO_HARDWARE
	}ENCODER_VIDEO_TYPES;

}

#endif // !ENCODER_VIDEO_DEFINE

